### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by lilijreey** [isagalaev/highlight.js#1075]
I use bower install highlight-js and run 'node tools/build.js -t brower'
I get a error message
/tmp/xx/bower_components/jj/tools/build.js:80
build     = require(`./${commander.target}`);
                    ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by sourrust** [comment]
The build script relies on ES6 features that are in node 4+ so if you want to build the library you need to update your node.
