### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by Daethe** [isagalaev/highlight.js#1085]
Hello, when i build the line-number branch i've this error. It's the first time i have this. I'll try using python 2.7 and python 3 but same issue.

```
Traceback (most recent call last):
  File "tools/build.py", line 304, in <module>
    build(buildfunc, root, args)
  File "tools/build.py", line 282, in build
    buildfunc(root, build_path, filenames, args)
  File "tools/build.py", line 213, in build_browser
    content = compress_content(tools_path, content)
  File "tools/build.py", line 110, in compress_content
    p = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Maybe my python install or the build.py file error. I don't know.

**Comment by isagalaev** [comment]
We've switched from Python over to node.js a long time ago… Please update the code to the latest version and [use the new building tool][b].

[b]: http://highlightjs.readthedocs.org/en/latest/building-testing.html
