### ISSUE TITLE
"Invalid range in character set" error when building with Webpack

### ISSUE THREAD

**Issue by sam-wheat** [isagalaev/highlight.js#1426]
When I am developing my site I run it using SystemJS and highlightjs works fine.
When I am ready to deploy I build it with Webpack and this is where the problem is.
I am still new to both SystemJS and Webpack so if I'm doing something completely wrong dont be surprised.
I would be very grateful if one of you could you could interpret the error message and tell me where to look.  As far as I know all the packages are current.  In any case, both SystemJS and Webpack should be reading from node_modules on my disk so I'm confused why one works and the other does not.
I am using Angular2 and typescript to build my site.  Here is my component that reads a text file from disk and highlights any code:

	var hljs = require('highlightjs');
	declare var highlight: any; // in site.js
	
	//.....

	private getContentItem(slug: string)
		{
			
			this.blogService.GetPostHtml(this.sessionService.PostRoot + this.Post.URL).subscribe((h: string) => {
										
				this.contentContainer2.nativeElement.innerHTML = h;
				
				highlight(hljs); // exists in js/site.js
	
			});
			
		}
	}

The relevent method is site.js:
	
	window.highlight = function (hljs) {
        var allPre, i, j;
        allPre = document.getElementsByTagName("pre");

        for (i = 0, j = allPre.length; i < j; i++) {
            hljs.highlightBlock(allPre[i]);
        }
    }

Again, the above works fine with SystemJS.  I only get an error with Webpack.
I call initHighlightingOnLoad() in my main method.  It appears to work fine with both SystemJS and Webpack so I don't show it.

Here is relevant portion of SystemJS.config.js:

	(function (global) {

    // map tells the System loader where to look for things
    var map = {
        'app': 'app', // 'dist',
        '@angular': 'node_modules/@angular',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        'rxjs': 'node_modules/rxjs',
        'highlightjs':'node_modules/highlightjs'
    };

    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
        'highlightjs': { main:'highlight.pack.min.js',  defaultExtension: 'js' }
    };

Webpack.common.js

	var webpack = require('webpack');
	var HtmlWebpackPlugin = require('html-webpack-plugin');
	var ExtractTextPlugin = require('extract-text-webpack-plugin');
	var helpers = require('./helpers');

	module.exports = {
		entry: {
			'polyfills': './wwwroot/app/polyfills.ts',
			'vendor': './wwwroot/app/vendor.ts',
			'app': './wwwroot/app/main.ts'
		},

		resolve: {
			extensions: ['', '.js', '.ts']
		},

		module: {
			loaders: [
			  {
				  test: /\.ts$/,
				  loaders: ['awesome-typescript-loader', 'angular2-template-loader']
			  },

			  {
				  test: /\.css$/,
				  loader: ExtractTextPlugin.extract("style-loader", "css-loader", {publicPath:"/build/"})
			  },

			  {
				  //test: /\.(jpe?g|png|gif|svg)$/i,
				  test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/i,
				  loaders: [
					  'file?hash=sha512&digest=hex&name=assets/[hash].[ext]',
					  'image-webpack?optimizationLevel=7&interlaced=false'
				  ]
			  }
			],

			preLoaders: [
			 //All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
			{ test: /\.js$/, loader: "source-map-loader" }]
		},

		plugins: [
		  new webpack.optimize.CommonsChunkPlugin({
			  name: ['app', 'vendor', 'polyfills']
		  }),

		  new HtmlWebpackPlugin({
			  template: './wwwroot/index-webpack.html'
		  }),

		  new webpack.optimize.UglifyJsPlugin({
				test: /\.(js|jsx)$/,
				minimize: true,
				sourceMap: true,
				mangle:false
		  }),

		  new webpack.ProvidePlugin({
			  $: "jquery",
			  jQuery: "jquery"
		  })
		]
		, devtool: 'source-map'
	};	
	

vendor exports:

	import '@angular/platform-browser';
	import '@angular/platform-browser-dynamic';
	import '@angular/core';
	import '@angular/common';
	import '@angular/http';
	import '@angular/router';
	import 'rxjs';
	import 'jquery';
	import '../../node_modules/bootstrap';
	import '../../node_modules/highlightjs';

	require('../../node_modules/bootstrap/dist/css/bootstrap.min.css');
	require('../../node_modules/highlightjs/styles/androidstudio.css'); 
	require('../css/site.css');
	require('../js/site.js');

package.json

	"dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "highlightjs": "^9.8.0",
    "jquery": "^3.1.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.2",
    "systemjs": "0.19.40",
    "ts-loader": "^0.8.2",
    "zone.js": "^0.7.4"
     },
    "devDependencies": {
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^3.0.0-beta.18",
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.0",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "image-webpack-loader": "^2.0.0",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.1",
    "typings": "^1.3.3",
    "webpack": "^1.14.0",
    "typescript": "^2.1.4",
    "webpack-dev-server": "^1.16.2",
    "webpack-merge": "^2.0.0",
    "html-webpack-plugin": "^2.26.0",
    "url-loader": "^0.5.7"
    }

Error message:

	EXCEPTION: Invalid range in character set
	core.umd.js (3486,1)
	ORIGINAL STACKTRACE:
	core.umd.js (3486,1)
	SyntaxError: Invalid range in character set
	   at s (http://www.x.com/build/polyfills.e82b7da4d27b1c1bf46d.js:2:10738)
	   at langRe (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:1844)
	   at compileMode (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:2297)
	   at Anonymous function (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:2947)
	   at Array.prototype.forEach (native code)
	   at compileMode (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:2782)
	   at compileLanguage (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:3232)
	   at highlight (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:5372)
	   at Anonymous function (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:5991)
	   at Array.prototype.forEach (native code)
	   at highlightAuto (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:5942)
	   at highlightBlock (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:165:6501)
	   at e.highlight (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:184:19500)
	   at Anonymous function (http://www.x.com/build/app.e82b7da4d27b1c1bf46d.js:22:26251)
	   at SafeSubscriber.prototype.__tryOrUnsub (http://www.x.com/build/vendor.e82b7da4d27b1c1bf46d.js:84:2687)
	core.umd.js (3486,1)
	SCRIPT5021: Invalid range in character set
	Subscriber.ts (241,7)

**Comment by sam-wheat** [comment]
For the benefit of the next poor soul that encounters this:  Turns out the error was caused by UglifyJsPlugin.  I removed all references to that plugin and I am back in business.
