### ISSUE TITLE
Build error: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by daituzhang** [isagalaev/highlight.js#1685]
I'm using highilght 9.12.0 on 
node 7.7.4
angular cli 1.5.6
webpack 3.5.6

when I do `ng build -- --prod --build-optimizer` got error below:
```
ERROR in ./node_modules/highlight.js/lib/languages/maxima.js
Module build failed: RangeError: Maximum call stack size exceeded
    at Object.visitEachChild (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51169:28)
    at visitor (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/src/transforms/import-tslib.js:33:27)
    at visitNode (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51053:23)
    at Object.visitEachChild (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
    at visitor (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/src/transforms/import-tslib.js:33:27)
    at visitNode (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51053:23)
    at Object.visitEachChild (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
    at visitor (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/src/transforms/import-tslib.js:33:27)
    at visitNode (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51053:23)
    at Object.visitEachChild (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
    at visitor (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/src/transforms/import-tslib.js:33:27)
    at visitNode (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51053:23)
    at Object.visitEachChild (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
    at visitor (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/src/transforms/import-tslib.js:33:27)
    at visitNode (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51053:23)
    at Object.visitEachChild (/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:51289:46)
 @ ./node_modules/highlight.js/lib/index.js 104:32-61
 @ ./src/app/components/component-code/component-code.component.ts
 @ ./src/app/components/page-header/page-header.component.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by jurStv** [comment]
Same error for me. Support needed!

**Comment by benny568** [comment]
Was there a solution for this? It's happening me with the last few days.

**Comment by jfinci1** [comment]
Me as well

**Comment by sunnyfly1990** [comment]
I have the same issue when building with 
```
Angular CLI: 1.7.4
Node: 6.9.5
```
Found the workaround in this [post](https://github.com/ag-grid/ag-grid-angular/issues/184), and it works for me. Still looking for any better solution.

> "prod": "node --stack_size=4048 node_modules/.bin/ng build --prod"

**Comment by Amryn** [comment]
Angular CLI: 1.7.4
Node: 8.11.1

Having the "Maximum call stack size exceeded"-error aswell. The workaround **sunnyfly1990** posted hasnt worked for me. Here is the log, if I increase the stack size:

<pre>
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\wagner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prod' ]
2 info using npm@5.7.1
3 info using node@v8.11.1
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle angular-pkw@0.0.0~preprod: angular-pkw@0.0.0
6 info lifecycle angular-pkw@0.0.0~prod: angular-pkw@0.0.0
7 verbose lifecycle angular-pkw@0.0.0~prod: unsafe-perm in lifecycle true
8 verbose lifecycle angular-pkw@0.0.0~prod: PATH: C:\Users\wagner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\wagner\PhpstormProjects\angular-pkw\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Users\wagner\AppData\Local\Microsoft\WindowsApps;C:\Users\wagner\AppData\Local\GitHubDesktop\bin;C:\Users\wagner\AppData\Roaming\npm
9 verbose lifecycle angular-pkw@0.0.0~prod: CWD: C:\Users\wagner\PhpstormProjects\angular-pkw
10 silly lifecycle angular-pkw@0.0.0~prod: Args: [ '/d /s /c',
10 silly lifecycle   'node --stack_size=4048 node_modules/@angular/cli/bin/ng build --prod' ]
11 silly lifecycle angular-pkw@0.0.0~prod: Returned: code: 3221225725  signal: null
12 info lifecycle angular-pkw@0.0.0~prod: Failed to exec prod script
13 verbose stack Error: angular-pkw@0.0.0 prod: `node --stack_size=4048 node_modules/@angular/cli/bin/ng build --prod`
13 verbose stack Exit status 3221225725
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid angular-pkw@0.0.0
15 verbose cwd C:\Users\wagner\PhpstormProjects\angular-pkw
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wagner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
18 verbose node v8.11.1
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 3221225725
22 error angular-pkw@0.0.0 prod: `node --stack_size=4048 node_modules/@angular/cli/bin/ng build --prod`
22 error Exit status 3221225725
23 error Failed at the angular-pkw@0.0.0 prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225725, true ]
</pre>

**Comment by yyyc514** [comment]
Still a problem for anyone?
