### ISSUE TITLE
tasks.js has syntax error

### ISSUE THREAD

**Issue by thoughtjigs** [isagalaev/highlight.js#979]
There is a syntax error in tasks.js that prevents building with gulp ...

return del(directories).then(() => done(null, blobs));

node_modules/highlight.js/tools/tasks.js:15
  return del(directories).then(() => done(null, blobs));
                                              ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (rtail/node_modules/highlight.js/tools/build.js:65:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

/home/tpci/rtail/gulpfile.js:86
      if (0 !== code) throw new Error('node tools/build.js exited with ' + cod
                                       ^
Error: node tools/build.js exited with 8
    at ChildProcess.<anonymous> (rtail/gulpfile.js:86:29)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by thoughtjigs** [comment]
If I rewrite the line as: 
return del(directories).then(done(null, blobs));
it compiles without error

**Comment by isagalaev** [comment]
We recently switched our toolchain to node 4.x, which version are you using?

**Comment by thoughtjigs** [comment]
ubuntu-trusty:~$ node --version
v0.10.37

**Comment by isagalaev** [comment]
This is probably the reason of it misbehaving. You might want to upgrade node.js to a contemporary release from a supported repository: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by sourrust** [comment]
Closing this since it isn't really a syntax error, at least for the new versions of node, but rather the build script using an ES6 feature called arrow functions.
